site_name: Kaizen - Better Than Yesterday
site_description: A Personal Knowledge Management System

theme:
  name: material
  language: en

  palette:
    # Light Theme
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark Theme
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Consolas
    code: JetBrains Mono

  favicon: assets/images/favicon.ico

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html

  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.highlight

  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/css/extra.css
