site_name: Kaizen &rarr; Continuous Improvement
site_description: Personal Backend Engineering Knowledge Base
site_author: Rohit Rajvaidya

theme:
  name: material
  language: en

  logo: assets/logo.png        # Optional
  favicon: assets/favicon.png  # Optional

  palette:

    # Dark Mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light Mode
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:

    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview

    - navigation.tabs
    - navigation.tabs.sticky

    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking

    # Search
    - search.suggest
    - search.highlight
    - search.share

    # TOC
    - toc.follow
    - toc.integrate

    # Code
    - content.code.copy
    - content.code.annotate

    # Markdown
    - content.tabs.link
    - content.tooltips

plugins:
  - search

markdown_extensions:

  - admonition

  - attr_list

  - md_in_html

  - tables

  - footnotes

  - toc:
      permalink: true

  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.superfences

  - pymdownx.details

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

  - pymdownx.emoji

  - pymdownx.keys

  - pymdownx.snippets

  - pymdownx.magiclink

extra:

  social:

    - icon: fontawesome/brands/github
      link: https://github.com/RohitRajvaidya5

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rohit-rajvaidya

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/checkbox.js
